### ISSUE TITLE
GRUの実装について。本ではバイアス項があるのに実装でないのは、なぜですか？

### ISSUE THREAD

**Issue by cedro3** [oreilly-japan/deep-learning-from-scratch-2#13]
GRUの実装についての問合せです。
本ではバイアス項が存在するのに、common / time_layers.py の実装ではバイアス項がないのは、なぜでしょうか？

**Comment by koki0702** [comment]
GRUのバイアス項を忘れているようです。
後ほど修正したいと思います。

ご指摘、ありがとうございます。
